### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by bwims** [mblackstock/node-red-contrib-influxdb#100]
Hello,

I just noticed that I am running 0.5.4 and 0.6.1 is available.  How can I find out what the differences are in a way that a non-developer can understand whether or not to upgrade?

Many thanks!

**Comment by mblackstock** [comment]
Here you go.  Hopefully that clears things up for you.

https://github.com/mblackstock/node-red-contrib-influxdb/releases
