### ISSUE TITLE
Delete measurement/Data points InfluxDB 2.0 [FEATURE REQUEST]

### ISSUE THREAD

**Issue by yonglizhong** [mblackstock/node-red-contrib-influxdb#102]
Hi all,

was wondering if anyone has attempted to delete data/measurements via this node-red package. I have successfully executed it with Postman. 

Is it possible with influxdb out node? Am asking because I had one for 1.8 version using influxdb-In node. Attempts have been futile so far. Not sure if it's absolutely impossible.

Or perhaps an alternative?

Thanks so much

**Comment by yonglizhong** [comment]
> Hi all,
> 
> was wondering if anyone has attempted to delete data/measurements via this node-red package. I have successfully executed it with Postman.
> 
> Is it possible with influxdb out node? Am asking because I had one for 1.8 version using influxdb-In node. Attempts have been futile so far. Not sure if it's absolutely impossible.
> 
> Or perhaps an alternative?
> 
> Thanks so much

With 1.8, it was the cli API that worked for me. Unfortunately, it doesn't seem to be the case here with InfluxDB 2.0.
![Capture](https://user-images.githubusercontent.com/55392228/122782848-57433a00-d2b1-11eb-8a42-503cf4b54f76.PNG)

**Comment by mblackstock** [comment]
I hadn't considered supporting delete.  Currently you can only write or query data.  Perhaps we need an 'API node', or a special mode of the output node to support this.

**Comment by yonglizhong** [comment]
Understood. I'll seek an alternative to execute such then. Shall I add this as a feature request?

**Comment by mblackstock** [comment]
Sure - this issue can serve as a feature request.
