### ISSUE TITLE
tag with false boolean not working

### ISSUE THREAD

**Issue by soleous** [mblackstock/node-red-contrib-influxdb#107]
Hi,

I am setting a boolean on a tag, but it's not getting into influxdb2.0 and only see true values.   I am doing it to the batch node, example of my function/payload:

```
msg.payload = [
    {
        measurement: "default",
        fields: {
            data: 1
        },
        tags:{
            sensor: "new",
            lowBattery: false
        },
        timestamp: new Date()
    }
]

return msg;
```

Thanks,

**Comment by AxelRHD** [comment]
I have the same problem. Seems to be not solved.

This is the tag-object:

```json
{
  "device": "LEQ0785938",
  "device_name": "Heizungsthermostat (Bad)",
  "room": "badezimmer",
  "from_cron": false
}
```

The `from_cron` value is missing when `false`.

**Comment by mblackstock** [comment]
Tags are stored as strings in influxdb so there's no point in using boolean values.  Try "true" and "false"

**Comment by AxelRHD** [comment]
> Tags are stored as strings in influxdb so there's no point in using boolean values. Try "true" and "false"

Okay, thank you for the fast response. I really missed that.
