### ISSUE TITLE
Hostname with http://, ignore verify cert check

### ISSUE THREAD

**Issue by ckbizpart** [mblackstock/node-red-contrib-influxdb#111]
I stumble upon one thing today on a Facebook group. I don't us this node my self so this is just one thing that may be improved.

The user had checked the: Verify server certificate and used a Hostname which started with http:// influxdb.Dockernetwork:8086 

I guess the http + verify should never be used together? And maybe should be handled automatic?

**Comment by mblackstock** [comment]
Yes, you can only very a server certificate using https.
