### ISSUE TITLE
Support InfluxDB 2.1

### ISSUE THREAD

**Issue by Dunnenj** [mblackstock/node-red-contrib-influxdb#113]
Is InfluxDB 2.1 supported? I tried a test flow for InfluxDB 2.0 without success.

**Comment by mblackstock** [comment]
I've tested with 2.0 and 2.1.  Is the issue with 2.0, 2.1 or both?  Could you give me more information on this issue, e.g. any error messages in the debug pane or console, your set up and your test flow?

**Comment by Dunnenj** [comment]
I started from scratch and now it is working fine. BTW I'm using v2.1.
