### ISSUE TITLE
Old Date using InfluxDB Batch Node not working

### ISSUE THREAD

**Issue by satyamtpatel** [mblackstock/node-red-contrib-influxdb#115]
When we are passing old date using influxdb batch node, it is not displaying data. We are sending in the Unix format and precision is in ms. Can you please provide assistance

**Comment by mblackstock** [comment]
Can you provide a sample flow that demonstrates the problem?

**Comment by satyamtpatel** [comment]
I was able to resolve the issue. Thanks for responding.
