### ISSUE TITLE
Timestamp field is not storing properly in influxDB bulk node

### ISSUE THREAD

**Issue by satyamtpatel** [mblackstock/node-red-contrib-influxdb#116]
We are inserting records from the past but time field is not displaying correct information.

For e.g.

We are sending unix time in msg.payload as a timestamp:  1598846404 

Date and time (GMT): Monday, August 31, 2020 4:00:04
Date and time (your time zone): Monday, August 31, 2020 0:00:04 GMT-04:00

 but in the influxDB it is storing as "2020-08-31T10:54:21.133Z"

Can you please provide your assistance?

**Comment by mblackstock** [comment]
Please ensure the timestamp has the correct precision e.g. milliseconds and
not seconds and provide a sample flow illustrating the problem.

**Comment by mblackstock** [comment]
Closing, will reopen if I get more information.

**Comment by satyamtpatel** [comment]
Sorry, I was able to resolve the issue. It is precision issue. Thanks for your support.
