### ISSUE TITLE
InfluxDB out Node RequestTimedOutError on InfluxDB 2 online

### ISSUE THREAD

**Issue by sbieri1** [mblackstock/node-red-contrib-influxdb#125]
Dear Authors

I am using a local dockered node-red instance (switzerland) aquiring data from an azure IoT-Hub and pushing data into an influxDB 2 **online** instance (deployed westeurope, ireland). I am using the influxdb out node (from node-red-contrib-influxdb, version 0.6.1) and writing every 0.5s. After some days of running perfectly fine, the whole node-red instance stops working. In the logs i get the following errors:
`````
WARN: Write to InfluxDB failed (attempt: 1). S [RequestTimedOutError]: Request timed out
    at ClientRequest.<anonymous> (/data/node_modules/@influxdata/influxdb-client/dist/index.js:16:4142)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:519:28)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.Socket._onTimeout (net.js:495:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
20 Jul 07:31:25 - [error] [influxdb out:Influx CtxGamma] RequestTimedOutError: Request timed out
`````
This message is repeated (thousands of times) for every trigger event until the node-red stops trying. After i restart the node (redeploy, not restart container), it continues working for maybe 4-5 days. On node-red there are no alarms, errors or what so ever. Can there be a way to either handle or configure timeouts?

**Comment by manelmg** [comment]
I have the same situation. I get these annoyings errors.
In my case I write into influxdb every 1 second.
Any possible solution to fix it or how to debug it?

**Comment by ChenChiang** [comment]
I am writing every 5s and receiving thousands messages of this error. 
Dose anyone have a solution?

**Comment by LangeWiese** [comment]
Since some weeks, I have the same problem with my communication between NodeRed and influxDB. NodeRed is running on a raspberryPi4 and influxDB in a docker container on my Synology. No one can help ? Best Regards
![IMG_3390](https://github.com/mblackstock/node-red-contrib-influxdb/assets/150428471/3b093dd7-defa-4130-8926-a972b1f431e0)

**Comment by tinooo** [comment]
having a very similar (or same) issue. After a few days, I'm receiving many errors. 

However, the infuxDB is receiving and logging the values properly. So for me everything seems to work fine, aside from many errors triggering.

InfluxDB is running locally on the same machine. I've tried to decrease the amount of messages, but without changes in the behavior.

**Comment by mblackstock** [comment]
Since this issue would be difficult to reproduce, requiring days of testing, and based on the report of a request timeout error, I decided to try adding a connection timeout feature (0.7.0) so that it's possible to increase the connection timeout.  Have you tried the latest version 0.7.0 and increasing the timeout to see if this addresses the problem in your setup?

**Comment by mblackstock** [comment]
Same as #134 assuming connection timeout feature fixes this unless I hear otherwise.

**Comment by tinooo** [comment]
Hi,
I've meanwhile tested the new feature, but it doesn't solve the issue. What I wan't to highlight, the data is being successfully written to the InfluxDB, no matter if I get the error or not.

And as mentioned, the error only starts to come  after a few hours/days.

However what is new with 0.7.0: There is a new Error:
![image](https://github.com/mblackstock/node-red-contrib-influxdb/assets/34310283/ee2c7e09-986d-43a0-a59d-4713f962a62a)

Both of these errors do come in bulk. And after some time, there is a bulk of the following errors:
![image](https://github.com/mblackstock/node-red-contrib-influxdb/assets/34310283/0170e450-f4b9-4c55-845d-e63e0d78e9fa)

Then it starts over.

Seems like the timeout does not have any effect. Please let me know if I can provide any further details or logs to help support you.

**Comment by mblackstock** [comment]
Hmm. It's not clear to me this is a node/client problem, but if I have time I will try looking into it.

Can you characterize the load and tell me what sort of machine you are running InfluxDb on?  i.e. how many writes, how much is written, what sorts of queries?  Does the load change before this happens?  What version of InfluxDb are you using (2.7.x)?  Perhaps you just need more resources (CPU, Memory) for the db or an upgrade to a newer version?

**Comment by tinooo** [comment]
okay, so here some infos:

- influxDB v2.7.1
- NodeRed v3.0.2
- node-red-contrib-influxdb v0.7.0

Everything running on a Synology NAS (DS220+ (Intel Celeron J4025 2-Core 2,0 GHz, Turbo bis 2,9 GHz ; 6GB RAM))
Setup everything using Docker on the NAS.
Overall ressource consumption of the NAS itself is quite low.
![image](https://github.com/mblackstock/node-red-contrib-influxdb/assets/34310283/9b5701d8-50b2-46c7-b1cc-b596531a3ff1)
Also as mentioned, the values seem to be received by InfluxDB. I don't find any values missing there.

My Requests are roughly:
~25 every 1 minute
~4 every 10 seconds
~30 every 15 seconds

So it is always a bulk that is triggered. e.g. with the 25 every minute, it roughly looks like this, and the result goes to the influxDb node.
![image](https://github.com/mblackstock/node-red-contrib-influxdb/assets/34310283/57e1a7e2-49a5-48eb-81ba-7b7082ef24d7)


The data per request is always similar. Some sensor data, with some tags. A typical message looks like this:
{
    payload: [{
        // _values here:
        temp: msg.payload*msg.topic.faktor,
    },
    {   //Tags here:
        prozesswert: msg.topic.name, 
        register: msg.topic.register,
        einheit: msg.topic.einheit 
    }]
};

everything either strings with 5-15 characters or some temperature, voltage, etc. values.


However, I've also tried with a delay node to reduce message load to 5msg/second. without change.
![image](https://github.com/mblackstock/node-red-contrib-influxdb/assets/34310283/818f95cf-0797-4790-bc33-e99a12509527)



thanks for your efforts. Let me know if I can be any more of a help.

**Comment by Bolukan** [comment]
Same issue: big amount of request time-outs, but influxdb is registering the data. Will watch this issue for news.

**Comment by Bolukan** [comment]
I solved my problem. 
I had to create a influxdb2 [config.json file](https://docs.influxdata.com/influxdb/v2/reference/config-options/) config file that is located in /etc/influxdb2. My guess is that some default configurations are otherwise set in a way that is far (too far) from optimal. 
So my advise: set some of the parameters manually (I used a config file, you can use try using docker environment variables):
  "http-idle-timeout":
  "http-read-header-timeout":
  "http-read-timeout":
  "http-write-timeout":
  "query-concurrency":
  "query-queue-size":
  "storage-wal-max-write-delay":
  "storage-write-timeout":
To view default settings, open the bash in your influxdb docker container and execute: influx server-config --token <your token>
don't trust '0' values, as that may generate far optimal settings.

**Comment by tinooo** [comment]
> I solved my problem. I had to create a influxdb2 [config.json file](https://docs.influxdata.com/influxdb/v2/reference/config-options/) config file that is located in /etc/influxdb2. My guess is that some default configurations are otherwise set in a way that is far (too far) from optimal. So my advise: set some of the parameters manually (I used a config file, you can use try using docker environment variables): "http-idle-timeout": "http-read-header-timeout": "http-read-timeout": "http-write-timeout": "query-concurrency": "query-queue-size": "storage-wal-max-write-delay": "storage-write-timeout": To view default settings, open the bash in your influxdb docker container and execute: influx server-config --token don't trust '0' values, as that may generate far optimal settings.

can you post the values you've used?
