### ISSUE TITLE
Feature request: Cache data if database unavailable

### ISSUE THREAD

**Issue by mr-manuel** [mblackstock/node-red-contrib-influxdb#136]
Would it be possible to add a caching function to not loose data during a connection or database outage?

If the database connection is not available the data gets stored on the disk and as soon as the database is available again, the data is written to the database.

There should also be a threshold for maximum cache size.

I would love it!

**Comment by mblackstock** [comment]
Thanks for the suggestion, but I think a general purpose data cache solution (node?) that could be used with other storage solutions might be a better solution.

**Comment by mr-manuel** [comment]
Do you know some?

**Comment by mblackstock** [comment]
Not offhand.  I recall a set of safe queue nodes that may be useful.  I suggest you bring up your need on slack or the forum so the wider community can help with a solution.
