### ISSUE TITLE
Dynamic measurement names

### ISSUE THREAD

**Issue by Benki** [mblackstock/node-red-contrib-influxdb#137]
Hi there,

is there a way to create dynamic measurement names from the payload (e.g. topic name) when writing to influx? 

Such as Measurement: ping.servers.{msg.payload.topic}

Thanks a lot.

Best regards
Benki

**Comment by mblackstock** [comment]
Yes, the documentation associated with the iout node describes this feature: "If the measurement field is not set in the node configuration, the user can send in data with a specified measurement name in msg.measurement to overwrite the measurement field in the configuration of the node."
