### ISSUE TITLE
Does not function in subflow passing the db via subflow properties

### ISSUE THREAD

**Issue by colinl** [mblackstock/node-red-contrib-influxdb#141]
In order to use the node in a subflow and configure the db using subflow properties it is necessary to configure the db node with subflow context.  In the db config node, when the node is inside a subflow, there should be a dropdown box allowing the subflow context to be set.  Each instance of the subflow will then have its own config node.  The dropdown box is not present.

To replicate the issue add an influxdb node to a subflow and add a new db config.  The dropdown at the bottom right is not present.

**Comment by mblackstock** [comment]
I suspect this may be a node-red-UI issue.  I noticed that the context pop-up is not there unless I expand the config node edit box by dragging the divider on the left until it appears.  This is the same behaviour for other nodes that have a narrower edit box.  I hope that helps!

**Comment by colinl** [comment]
I think you are correct. Sorry for the noise.

**Comment by mblackstock** [comment]
No problem.  I think this is confusing.  IMHO, the config editor should be wider by default, but I will try to fix it for my node at least.

**Comment by colinl** [comment]
I have submitted an issue against node-red as it would be good if the core coped with this better.  https://github.com/node-red/node-red/issues/4497

**Comment by mblackstock** [comment]
Agreed - that's why I demonstrated the problem with core nodes in the forum.

**Comment by colinl** [comment]
Yes, I realised that.  I posted the link to the issue so that anyone else who finds this issue will be able to check the status of the issue.
