### ISSUE TITLE
Request Timeout Error In InfluxDB in node in nodered

### ISSUE THREAD

**Issue by Lin-Pyae** [mblackstock/node-red-contrib-influxdb#142]
I recognized that requesting to influxdb from nodered with approximately more than 10s long query resulted in RequestTimedOutError: Request timed out.

The problem is that my request to influxb from nodered takes pretty much times. I was wondering is there any other way I can increase timeout or is there any alternative way to wait that query without getting timeout error and get the result from influxdb instead.

**Comment by mblackstock** [comment]
Did you try increasing the connection timeout?

**Comment by Lin-Pyae** [comment]
![Screenshot from 2024-01-09 10-03-40](https://github.com/mblackstock/node-red-contrib-influxdb/assets/82535259/d45e3817-2d7b-457c-96e0-5ec495904c2e)

I found no timeout increasing option in influxdb in node.

**Comment by mblackstock** [comment]
It is in Version 0.7.0 and only works for 1.8 and 2.0 versions.  The option is in the configuration node where the connection URL is configured.  You can set the timeout in seconds. 
![Screen Shot 2024-01-09 at 5 34 17 PM](https://github.com/mblackstock/node-red-contrib-influxdb/assets/707704/e2c15902-6e42-4599-9204-4f59c772d4b8)

**Comment by mblackstock** [comment]
Same as #134.  Please re-open that issue if new feature doesn't work for you after testing it.

**Comment by Lin-Pyae** [comment]
I found no option for timeout like you in the configuration node too.
![image](https://github.com/mblackstock/node-red-contrib-influxdb/assets/82535259/3a82f341-fe66-44d0-8697-b329f5f68099)
