### ISSUE TITLE
Spam of dns requests

### ISSUE THREAD

**Issue by ghost** [mblackstock/node-red-contrib-influxdb#145]
I recently noticed in PiHole that NodeRed sends many DNS requests for my domain for InfluxDB. As you can see underneath about 1.200 DNS requests are sent within 10 minutes which is a lot. Is there any way to fix that? If you need more information, please just let me know.

![image](https://github.com/mblackstock/node-red-contrib-influxdb/assets/35005352/1508a5ee-f2c7-4106-adb3-8a8c1e42b340)

![image](https://github.com/mblackstock/node-red-contrib-influxdb/assets/35005352/86991f63-c455-47e7-b82a-1aa24f79f286)

![image](https://github.com/mblackstock/node-red-contrib-influxdb/assets/35005352/90b59298-5437-44e3-8f6e-0fbe65c78a4b)

**Comment by ghost** [comment]
Never mind, You have to change the local-ttl in PiHole. See [here](https://discourse.pi-hole.net/t/change-the-ttl/6903)

**Comment by youzer-name** [comment]
@marcx28  Did setting local-ttl in PiHole fix this for you? I set local-ttl to 600 and can see (using dig) that that the DNS server is responding with that value, but my Node Red InfluxDB nodes still send a new DNS query every few seconds.

**Comment by ghost** [comment]
@youzer-name Unfortunately not. The first hour after changing the local-ttl it looked fine but afterwards I had still a lot of dns requests. I gave up looking for a solution ☹️
