### ISSUE TITLE
15 Jun 13:47:18 - [error] [influxdb out:6c73de65.8cb15] Error: self signed certificate

### ISSUE THREAD

**Issue by industrialinternet** [mblackstock/node-red-contrib-influxdb#20]
Mike, I'm running influxdb 1.1 on a RPI far a long while.
I've just added HTTPs to influx using a self singed cert as per
https://docs.influxdata.com/influxdb/v1.2/administration/https_setup/#setup-https-with-a-self-signed-certificate. 

HTTPS is working, I can connect using Grafana and the old influx web ui.
I get the error 
15 Jun 13:47:18 - [error] [influxdb out:6c73de65.8cb15] Error: self signed certificate

Feels like the issue is in node-influx?
Any thoughts.

All best
Lawrence

**Comment by mblackstock** [comment]
Hmm.  Can you send me the flow file?  I'd like to check the configuration.  The flow should have a TLS configuration with Verify Server Certificate unchecked (false).  Are you using the latest version of this node - 0.2.0 or an older one?  I'll do another quick test to make sure the latest node is working as expected with a similar configuration when I can.

**Comment by industrialinternet** [comment]
I'm not using the latest let me update before you start diggin

**Comment by industrialinternet** [comment]
Mike have upgraded to latest version & problem sorted 
Many thanks

**Comment by mblackstock** [comment]
awesome 👍
