### ISSUE TITLE
A 400 Bad Request for some object keys

### ISSUE THREAD

**Issue by Bouni** [mblackstock/node-red-contrib-influxdb#21]
I try to insert a bunch of values that I query from my heatpump controller but for some of the values I get an *A 400 Bad Request*.
At first i thought that it is caused by the Umlauts but they work for some values, so I have no idea what causes this problem.
This is the object I send into the out node (copy&past from the debug panel, so not properly json formated ;-) ):
```
Vorlauf: 32.5
Rücklauf: 30.1
Rückl.-Soll: 15
Rückl.-Extern: 24.9
Heissgas: 28.8
Aussentemperatur: 34.3
Mitteltemperatur: 23.3
Warmwasser-Ist: 49
Warmwasser-Soll: 50
Wärmequelle-Ein: 24.2
Wärmequelle-Aus: 24.4
Mischkreis1-Vorlauf: 24.3
Mischkreis1-VL-Soll: 20
Solarkollektor: 5
Solarspeicher: 150
Externe-Energ.Quelle: 5
Vorlauf-max.: 64
Ansaug-VD: 29.5
Überhitzung: 5
Überhitzung-Soll: 6
```

And that's the error message:

```
Error: A 400 Bad Request error occurred: {"error":"unable to parse 'temperatures Ansaug-VD=29.5,Aussentemperatur=34.3,Externe-Energ.Quelle=5,Heissgas=28.8,Mischkreis1-VL-Soll=20,Mischkreis1-Vorlauf=24.3,Mitteltemperatur=23.3,Rückl.-Extern=24.9,Rückl.-Soll=15,Rücklauf=30.1,Solarkollektor=5,Solarspeicher=150,Vorlauf=32.5,Vorlauf-max.=64,Warmwasser-Ist=49,Warmwasser-Soll=50,Wärmequelle-Aus=24.4,Wärmequelle-Ein=24.2,Überhitzung=5,Überhitzung': invalid field format"}
```

If I reduce the object to the first 7 elements, it works, but when I include "Warmwasser-Ist" I get the error.
It doesnt's make sense to me at all.

**Comment by Bouni** [comment]
Update from 0.1.1 to 0.2.0 fixed the issue for me. Sorry for the unnecessary issue.

**Comment by mblackstock** [comment]
👍
