### ISSUE TITLE
Influx DB query node won't return multiple measurements properly

### ISSUE THREAD

**Issue by candronikos** [mblackstock/node-red-contrib-influxdb#23]
When using a query node for multiple measurements the data is all concatenated together. So it isn't clear what segment of data belongs to which measurement.

Is there a way to make it return a dictionary for each measurement with the key being the measurement name?

**Comment by mblackstock** [comment]
I'm hoping the new 'Raw Output' checkbox in the query node gives you what you need.  We added this recently.  Let me know.

**Comment by candronikos** [comment]
This is what I ended up using
