### ISSUE TITLE
FEATURE REQUEST: Reconfigure influx node at runtime

### ISSUE THREAD

**Issue by candronikos** [mblackstock/node-red-contrib-influxdb#25]
Would be more useful if all the configuration entered in the UI could be altered via a new node.

This would mean that the flows could be scaled and the only difference between them would be the JSON passed to it at startup.

What do you think?

**Comment by mblackstock** [comment]
Thanks for the feedback.  How would allowing a new node to change the configuration improve scalability?  How would you wire up the configuration node to another node since configuration nodes are not on the canvas?

To scale up could you not have multiple instances of NR accessing the same InfluxDb server or cluster?  Currently I don't support more than one influxdb host (cluster), but could probably add a UI to support multiple hosts to the config node.  Is that what you're looking for?

**Comment by candronikos** [comment]
I should probably say that it makes deployment easier. I find that if I copy the flows through the browser I don't have the credentials. But the credentials wouldn't be the same anyway in our case. At least between instances of node-red.

Each one would be pointing to a different database at least but could be a different instance of influx all together. Personally, I would prefer to keep these config settings separate from the implementation. That way we can maintain a single flow and just alter the config on a server by server basis.

**Comment by mblackstock** [comment]
I see what you mean.  You want the node configuration (influxd host, credentials) to be configurable depending on the deployment (for example using environment variables or in settings.js file) that are set differently for testing and production.

I think this idea, or something close to it has been discussed on the NR mailing list https://groups.google.com/forum/#!topic/node-red/qTlYWKF-Nrw

It looks like this may have been addressed by a little known NR feature: "_A not-well-publicised feature we added a couple releases ago is the ability to reference environment variables directly in any node property. If you set a node property to $(NAME), then the runtime will automatically substitute that with the corresponding environment variable before it is passed to the node_."

So in theory, you can set the host name, credentials in this node and others using environment variables that are set differently for each deployment.  Haven't tried it yet though.  Not sure how/whether it would work for credentials.  Maybe give that a try.

Either way, I think this is an issue that affects pretty much every node, especially database nodes, not just this one, so perhaps it's worth raising on the mailing list again if it doesn't work.

**Comment by candronikos** [comment]
Sounds good! Will investigate and report back!

**Comment by mblackstock** [comment]
haven't heard back, so I'll assume you're good!
