### ISSUE TITLE
Write tag with specific timestamp

### ISSUE THREAD

**Issue by jvondrus** [mblackstock/node-red-contrib-influxdb#27]
Hello,
is possible to write data to database with specific timestamp?

I'm handling with data from MQTT and sometimes data has a delay (due connection issue). They are written to database with same timestamp when they all come. My option is sending timestamp at MQTT message and use it for timestamp for Influx.

Thank you.

**Comment by mblackstock** [comment]
Yes, I believe the README covers this, using the "time" field when you are writing the data.

**Comment by jvondrus** [comment]
Hello, sorry, problem was on my side. I had a wrong setting with retention policy. All works great.

**Comment by mblackstock** [comment]
Super!  Thanks for using this node.

**Comment by jvondrus** [comment]
Hello, unfortunately, there is a problem with timestamp "size".

Timestamp at node is in millis (13 numbers) but influx is based on nanos (19 numbers), and doesn't matter how time precision is setup (it just mask most right numbers by 0, but still has 19 numbers).  So you have to **multiply generated timestamp by 1000000** for get right size of timestamp for influx inject.

`var time    = new Date().getTime() * 1000000;`

**Comment by stoinov** [comment]
This is still the case - I am using `fields.time = Date.now();` and I get `ms` precision which influx still assumes is `ns` and this leaves my measurements about 25 minutes in the 1970.

can you make  the check automatic and handle the multiplication during the input. Maybe make it a selectable option - "Convert all inputs to `ns` precision" Or just make a note in the readme as this took me a while to figure out.

**Comment by stoinov** [comment]
Best option - just add drop-down with the available [precision in HTTP](https://docs.influxdata.com/influxdb/v1.7/tools/api/#write-http-endpoint)

**Comment by stoinov** [comment]
Sorry for the spam, but one important asterisk from the link:

> ** We recommend using the least precise precision possible as this can result in significant improvements in compression.

As JS does not have more than `ms` precision, it's best to use this by default to help with the compression.

**Comment by stoinov** [comment]
Final comment  - I saw in code that you actually handle this parameter with `msg.precision`. But in the readme it's only mentioned in the batch node, so this could be updated to better reflect it.
