### ISSUE TITLE
Insert all topic From mqtt

### ISSUE THREAD

**Issue by twilingway** [mblackstock/node-red-contrib-influxdb#28]
Hello.
How Can I insert to InfluxDB from all topic mqtt?
I used Node -red Mqtt # -> influxDB out 
What me need to insert in Measurement that would get the name of topics?

**Comment by mblackstock** [comment]
Hi - you can do this by ensuring format of the data that you receive from the MQTT input node to match the data format(s) supported by the influxdb output node.  You can do this with function nodes, or change nodes for example.  I can't help you with this without knowing what the format is of the data you are attempting to insert into InfluxDB

The README should be able to help.  Look at the section on the "Output Node" for examples.  Let me know if the examples are not working or if there is something you don't understand there.

**Comment by mblackstock** [comment]
I am not sure what you mean by 'boxes'.  Do you mean physical devices?  I can't help you with the hardware.

Sounds like you are having trouble creating a flow that converts the data from your devices to the format required for this node?  If so, the Node-RED community and documentation should be able to help.

The README should be able to help you get the message format right. Look at the section on the "Output Node" for examples. Let me know if the examples are not working or if there is something specific in the examples that you don't understand, or you find a bug in this node.
