### ISSUE TITLE
self signed certificate influxdb connection

### ISSUE THREAD

**Issue by timoline** [mblackstock/node-red-contrib-influxdb#31]
Hello howto make a connection with influxdb with a self signed certificate in node-red? (-unsafeSsl)

**Comment by mblackstock** [comment]
You can configure the node to use a tls configuration similar to the built in MQTT and HTTP request nodes.  To do this, check 'Enable secure (SSL/TLS) connection', then click on 'add new tls-config...' 
 In this dialog, make sure that the 'verify server certificate' checkbox is unchecked.  There's no need to provide other certificates here.

If that doesn't work, let me know.

**Comment by timoline** [comment]
Ok thx, I'll try it

**Comment by timoline** [comment]
little request...

For consistency ... can you make it like the mqtt node?
with a connection tab and security tab?

**Comment by mblackstock** [comment]
I'll have a look, but lets open another issue for this, rather than overloading this one.  Did you manage to get self signed certs working?

**Comment by timoline** [comment]
Ok, thx
I did not manage to get it working yet.....
I'm struggling....I'm not sure where the problem is:
- influxdb.conf
- or the correct cert.
- or in the grafana node

**Comment by mblackstock** [comment]
Tested latest code locally with a self signed certificate as described in https://docs.influxdata.com/influxdb/v1.6/administration/https_setup/#step-1-generate-a-self-signed-certificate

Just needed to "Enable secure (SSL/TLS) connection" leaving all config blank/empty.
