### ISSUE TITLE
Unable to write a value to influxdb

### ISSUE THREAD

**Issue by Mihara** [mblackstock/node-red-contrib-influxdb#36]
I am trying to write an MQTT message to influxdb, and getting strange results. The message originates in [OwnTracks](https://owntracks.org/booklet/), so it looks like so:
```
{
  "_type":"location",
  "acc":39,
  "alt":195,
  "batt":61,
  "conn":"w",
  "inregions":["Home"],
  "lat":55.0,
  "lon":37.0,
  "t":"p",
  "tid":"s5",
  "tst":1548442037,
  "vac":16,
  "vel":0
}
```

I am feeding it through the json parse node and straight into influxdb, and getting this error back:
```
Error: A 400 Bad Request error occurred: {"error":"unable to parse 'track _type=\"location\",acc=39,alt=195,batt=61,conn=\"w\",inregions=Home,lat=55.0,lon=37.0,t=\"u\",tid=\"s5\",tst=1548436524,vac=16,vel=0': invalid boolean"}
```
Other sources of data logged into influxdb, which are also blocks of json taken straight out of MQTT messages, do not have any problems, and I can't help but notice that something strange happened to `inregions`. Am I doing something wrong, or are arrays of strings not being handled correctly?

**Comment by mblackstock** [comment]
Was this a problem with your flow, or is it still an issue for you?

**Comment by mblackstock** [comment]
Stale - closing.
