### ISSUE TITLE
influxdb out inserts two records (duplicates)

### ISSUE THREAD

**Issue by churruscat** [mblackstock/node-red-contrib-influxdb#37]
when I inset one record in an influxdb database I get the record inserted twice with a very little difference in time:
Record format (passed as msg.payload):
![Capture](https://user-images.githubusercontent.com/26358073/54670572-37ca6f00-4af4-11e9-9173-222977736c1a.PNG)

If I query the database

```
> Select * FROM meteo WHERE time >= '2019-03-20T08:05:00Z' and "deviceId"='Jardin' limit 2
name: meteo
time                           HPa  deviceId hAire hCrudo hSuelo l/m2 temp
----                           ---  -------- ----- ------ ------ ---- ----
2019-03-20T09:09:13.709229151Z 1030 Jardin   56    195    36     0    7.1
2019-03-20T09:09:13.712843732Z 1030 Jardin   56    195    36     0    7.1
>
```

I only call influxdbout once, but there are two records with less than 4/1000 of a second difference.
Is this a known bug or I am doing something wrong? (I have not found it reported)
Regards

**Comment by mblackstock** [comment]
Is it possible the same record was written twice by the flow or is this still a problem for you?

**Comment by churruscat** [comment]
Thanks. The flow was working correctly. I reinstalled the whole set: influxdb, moquitto and node-red and now it works.
