### ISSUE TITLE
Insert value + tags

### ISSUE THREAD

**Issue by tnq13** [mblackstock/node-red-contrib-influxdb#4]
Hello!

Your contribution is really helping me! Thank you!
I'm already able to insert data into my Influx database, but there's something to be done so it would be perfet!

How would I add tags to the valeu?

The name of my measurement is "variaveis"
I want to add information on "value" --this is working
But also want to complete "desc" and "tag" values... and this is my problem. Would you help me?

Thanks in advance!

![captura](https://cloud.githubusercontent.com/assets/25102264/22001386/f485eafa-dc2b-11e6-85eb-cc2228cf6bd5.jpg)

**Comment by mblackstock** [comment]
Hi,

You can create a message with a both value fields and tags as described in the README.  To do so, you supply an array of two objects.  The first object has the fields, the second object contains the tags.  

"If msg.payload is an array containing two objects, the first object will be written as the set of named fields, the second is the set of named tags."

```
msg.payload = [{
    numValue: 12,
    randomValue: Math.random()*10,
    strValue: "message2"
},
{
    tag1:"sensor1",
    tag2:"device2"
}];
return msg;
```

Let me know if this answers your question.

**Comment by tnq13** [comment]
In fact, I've saw it before and tried without success. I know barely
nothing regarding JS, what complicates everything...



Em 17 de jan de 2017 12:01 AM, "Mike Blackstock" <notifications@github.com>
escreveu:

Hi,

You can create a message with a both value fields and tags as described in
the README. To do so, you supply an array of two objects. The first object
has the fields, the second object contains the tags.

"If msg.payload is an array containing two objects, the first object will
be written as the set of named fields, the second is the set of named tags."

msg.payload = [{
    numValue: 12,
    randomValue: Math.random()*10,
    strValue: "message2"
},
{
    tag1:"sensor1",
    tag2:"device2"
}];
return msg;

Let me know if this answers your question.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mblackstock/node-red-contrib-influxdb/issues/4#issuecomment-273002807>,
or mute the thread

**Comment by mblackstock** [comment]
Just retested the node with the flow in the read me and the latest version of influxdb, and I'm able to insert fields and tags as documented.  Please send an email to support@sensetecnic.com or contact me directly if you have any questions on Node-RED, our FRED service, and one of us can give you a hand.  Closing this issue
