### ISSUE TITLE
Added support for for influxdb chunk for large datasets

### ISSUE THREAD

**Issue by wtthornton** [mblackstock/node-red-contrib-influxdb#41]
Trying to utilize influxdb and tensorflow to train from large datasets. Would like to 'stream' the query, transform it to tensorflow dataset to be consumed by tensorflow js.  If this is out of scope of this project, please let me know.

**Comment by mblackstock** [comment]
This node just allows your node-red flows to insert and query influxdb, and has nothing to do with tensorflow.  This node may be part of your solution, but you'd need to put together your own flow, probably using additional nodes for transformation of the messages and tensorflow integration.  There are likely resources on line that can help you along, including the node-red slack channel and discussion board.  see https://nodered.org/

**Comment by wtthornton** [comment]
Thank you for the quick response.  Agree this has nothing to do with
tensorflow, I apologize for the confusion.  The issue I am having is we can
chuck or stream the data.    Running a query that returns a million rows of
historical data is causing influxdb to run out of memory. I wanted to see
if the chunking parameter in influxdb would possibly help.  Very new to
influxdata and node-red. So this might now be possible or helpful.

https://docs.influxdata.com/influxdb/v1.7/guides/querying_data/

Chunking can be used to return results in streamed batches rather than as a
single response by setting the query string parameter chunked=true.
Responses will be chunked by series or by every 10,000 points, whichever
occurs first. To change the maximum chunk size to a different value, set
the query string parameter chunk_size to a different value. For example,
get your results in batches of 20,000 points with.

curl -G 'http://localhost:8086/query' --data-urlencode "db=deluge"
--data-urlencode "chunked=true" --data-urlencode "chunk_size=20000"
--data-urlencode "q=SELECT * FROM liters"
