### ISSUE TITLE
Some Errors in NodeRed Logs

### ISSUE THREAD

**Issue by soloam** [mblackstock/node-red-contrib-influxdb#42]
Hello, I have a influxdb nonde inserting records into my InfluxDb Database, the problem is that sometimes, without apparent reason, I get:

Error: Internal Server Error
Error: No host available

What is the timeout? My hosts are always available!

Thank you

**Comment by soloam** [comment]
This problem is making me lose some data, I can't validate if the data was saved to the database, or not! 

Thank you

**Comment by mblackstock** [comment]
Thanks for the report. It may be related to this issue:  https://github.com/node-influx/node-influx/issues/171 and https://github.com/node-influx/node-influx/issues/178
since this node is simly a wrapper on node-influxdb.  Perhaps batching up writes will help.

**Comment by mblackstock** [comment]
Closing since no further information was provided.
