### ISSUE TITLE
Support for InfluxDB 2.0 Cloud

### ISSUE THREAD

**Issue by ConBeeUser** [mblackstock/node-red-contrib-influxdb#43]
Hi, thank you for your node-plugin!

I've not been able to test it yet as I'm using the 2.0 Cloud version of InfluxDB.
Please excuse my usage of the "Issue-Tracker" as I don't know how to start a normal conversation over here. 

May it be possible to support the InfluxDB 2.0 Cloud (API) to write (and read) to the InfluxDB Cloud database?
I would like to run InfluxDB in the cloud as my Node Red instance runs on an internet server, too. Bus therefore I cannot run InfluxDB on a local machine.

I would be very grateful.
Thank you! Best regards!

**Comment by mblackstock** [comment]
Thanks.  Good idea.  I'll look into what it might take to support it.

Currently this node is a wrapper on the node-influxdb client library (
https://github.com/node-influx/node-influx).  It doesn't look like this
node supports the new API yet.  Not sure whether its worth extending this
node or creating a new one...

Mike

**Comment by ConBeeUser** [comment]
Hi Mike! 
Thank you for your quick answer!

Ah ok, I see. That doesn't sound like there is an easy solution.
Maybe node-influx gets updated some time.

So don't worry, I'll stay tuned ;-)
Thank you and best regards!
Matthias

**Comment by mblackstock** [comment]
closing this since it duplicates #50.  Will track it there.
