### ISSUE TITLE
Add explicit outpouts to the influx out and influx batch nodes

### ISSUE THREAD

**Issue by malcolmwhat** [mblackstock/node-red-contrib-influxdb#48]
On the same vein as the error handing in #46 would it be ok to add result handling for successes of influx writes?

What I'm thinking is we add an output to influx batch with a `.then` on the writePoints which sends a message containing the `204` for the successful write.

Should I add this to the influx batch node or do you think it belongs in a separate node?

**Comment by mblackstock** [comment]
Not sure I understand.  Are you suggesting adding  an HTTP status code to the message when there is no error or exception thrown?  I don't think we should do that.

**Comment by malcolmwhat** [comment]
That was the idea, but yeah, reading this back a few days later it doesn't really make sense.. The basic error handling is more than enough to handle out of the ordinary cases of timeouts or anything like that and the positive response is not needed. Thanks anyway
