### ISSUE TITLE
Configuration is missing in node-red API GET request

### ISSUE THREAD

**Issue by SalehAly** [mblackstock/node-red-contrib-influxdb#5]
Hey, 

I am not sure if this is an issue with `node-red-contrib-influxdb` or `node-red` themselves, so I would ask you first.

The issue is; when you GET a flow which includes an influxdb node via node-red API `GET localhost:1880/flow/{id}`, the configuration of the influxdb node is not included in the response. So, if you POST the same flow in another node-red instance for example you get 
`[error] [influxdb out:2ebbdce2.4d8274] Configuration missing`

However, the configuration can be found if you export the same flow via the node-red UI

An example of the missing config
 ```js
 {
    "id": "24b1fa97.98b266",
    "type": "influxdb",
    "z": "",
    "hostname": "127.0.0.1",
    "port": "8086",
    "protocol": "http",
    "database": "images",
    "name": ""
  } 
```
Thank you

**Comment by mblackstock** [comment]
I'm not familiar with the flow API - I will have a look.  First thing I will do is see if this issue occurs with other nodes with similar configuration and set up such as the mongodb node.  If it does, it's a node-red API issue.  I suspect it has something to do with configurations not being associated with a specific tab, so if you request the flow for a tab (z), you get only the nodes on that tab, not the configurations, but need to confirm.

**Comment by SalehAly** [comment]
Hey, 

Thank you for your response, 

I decided to save you time and carry out what you have suggested, and your speculation was correct I think it is indeed issue with node-red because the same issue happened with mongodb node. 

API

```js
{
  "id": "4880e9bc.a5c798",
  "label": "Flow 2",
  "nodes": [
    {
      "id": "126af684.cc3459",
      "type": "mongodb out",
      "z": "4880e9bc.a5c798",
      "mongodb": "5efe8db7.bf6ee4",
      "name": "",
      "collection": "test",
      "payonly": false,
      "upsert": false,
      "multi": false,
      "operation": "store",
      "x": 324.5,
      "y": 263,
      "wires": [
        
      ]
    }
  ]
}
```

Export
```js
[
    {
        "id": "126af684.cc3459",
        "type": "mongodb out",
        "z": "4880e9bc.a5c798",
        "mongodb": "5efe8db7.bf6ee4",
        "name": "",
        "collection": "test",
        "payonly": false,
        "upsert": false,
        "multi": false,
        "operation": "store",
        "x": 324.5,
        "y": 263,
        "wires": []
    },
    {
        "id": "5efe8db7.bf6ee4",
        "type": "mongodb",
        "z": "",
        "hostname": "127.0.0.1",
        "port": "27017",
        "db": "mongo",
        "name": ""
    }
]
```
