### ISSUE TITLE
InfluxDB v2.0

### ISSUE THREAD

**Issue by justinkalland** [mblackstock/node-red-contrib-influxdb#50]
Aloha, thanks for your node contribution, I use it a lot! I am migrating some systems to Influx 2 and currently I am just using raw queries in Node-RED to interact with InfluxDB2 API. I was considering making a new set of contrib nodes specifically for InfluxDB 2, but wanted to get your take on it first. Do you think a new project is justified? Or perhaps you would like to roll support for V2 into this project? The official node client is out and works great.

Here are some references:

- [INfluxDB 2.0 Overview](https://www.influxdata.com/products/influxdb-overview/influxdb-2-0/)
- [InfluxDB v2.0 Documentation](https://v2.docs.influxdata.com/v2.0/)
- [Influx API Service (full API Docs for v2)](https://v2.docs.influxdata.com/v2.0/api/)
- [Official InfluxDB 2.0 JavaScript client](https://github.com/influxdata/influxdb-client-js)

**Comment by mblackstock** [comment]
I think it would be great to support Influx 2.0 with this project. Fewer
nodes for supporting Influx would be better I think; at least make it
easier to find the node.

I'd be glad for your help if you're interested.  Maybe we can introduce the
new client as a dependency and add a version configuration?  What do you
think?  As you've probably seen already, the code is pretty simple.

**Comment by justinkalland** [comment]
I think adding support into this set of nodes is a great idea, but many choices will have to be made. I started to tinker with it as a version setting in the database config node. Interacting with v2 can be very different, such as the new query language [Flux](https://www.influxdata.com/blog/influxdb-2-0-alpha-release-and-the-road-ahead/). It also seems there is language differences in Influx 2, such as "buckets".

**Comment by mblackstock** [comment]
I see.  It might be good to create an additional node or two to support the
new features.  I'll have a look.  If you have any specific ideas, let me
know.

**Comment by timoline** [comment]
Hello,
is there any progress or roadmap for this feature?

**Comment by salvq** [comment]
I am using new flux scripting lang and it is very powerful.

Having this feature would very much appreciated.

**Comment by aarmijo** [comment]
Hi @mblackstock,  I'm working on adding nodes for supporting InfluxDB 2.0 and InfluxDB 1.8 Flux using the 2.0 compatibility API. A Pull request will be published soon for your consideration.
