### ISSUE TITLE
Timestamp issue in samples

### ISSUE THREAD

**Issue by ChrisCA** [mblackstock/node-red-contrib-influxdb#53]
I today detected an issue when using the "out" node.
We tried to use the provided sample but the inserted sets were always dated to UNIX start date in 1970. After some time we recognized that everything works fine if we do not use the ".getTime()" for the Date object.

I used:
InfluxDB: 1.7.10
node-red-contrib-influxdb 0.4.0
Node-RED 1.0.4 on latest non-LTS NodeJS

Couldn't figure out whether this is already fixed.

**Comment by weirders** [comment]
Same issue here, but removing getTime() doesnt work either. 
I'm pretty much stuck now. Any other ideas?

**Comment by mattocchi** [comment]
Same issue with Output Node case "if msg.payload is an array of arrays", as example, points with "time" property are not saved to influx (".getTime()" or not not solve the problem).

InfluxDB: 1.7.9
node-red-contrib-influxdb: 0.4.0
Node-RED: 1.0.3
NodeJs: v10.13.0
