### ISSUE TITLE
Writing with retention Policies

### ISSUE THREAD

**Issue by magtimmermans** [mblackstock/node-red-contrib-influxdb#56]
Hi,

Thanks for your node contribution, I use it a lot and really handy! 

When using retention policies, the data does not end up in the measurements. If you check the log file you will see a 204 http return code that will say it is cached. But somehow it is not ending up into the DB.

Could you please check this?

**Comment by sovaCode** [comment]
Hi,

I am facing the same problem.

Has anybody found a solution?

Best Regards

**Comment by sovaCode** [comment]
Hi,

please check this post:
https://community.influxdata.com/t/influxdb-not-write-data-when-i-specified-retention-policy/13068
maybe that is the issue.

Best Regrads

**Comment by mblackstock** [comment]
Have you confirmed this is the issue?  If so, I will close it.

**Comment by mblackstock** [comment]
Closed - no response
