### ISSUE TITLE
Write to influxDB interval

### ISSUE THREAD

**Issue by henjoe** [mblackstock/node-red-contrib-influxdb#59]
Dear Sir, may I know if there is a limitation to write data on influxDB? 
I have this data that updates data every 100ms interval, what I want is to write data to influxDB using the influxdb out node at that speed interval (100ms), but I notice that on my database my data is in somehow 1-5s interval (randomly). I am just thinking that is there any limitations on the speed to write data in influxdb out? 
Thank you.

Looking forward.

**Comment by mblackstock** [comment]
I'm not sure where the bottleneck may be since I haven't seen your flow, but If you're finding the out node can't write fast enough you could try buffering up several data points and write them at the same time.
