### ISSUE TITLE
Multiple measurement at the same time

### ISSUE THREAD

**Issue by bnjroos** [mblackstock/node-red-contrib-influxdb#6]
First, thank you for your influx node for nodered.

I have a question, is there a way to send multiple different measurements at the same time ? A few is ok but when I increase the number, the influxdb node will send me a timeout error.

Thank you for your help.

Benjamin

**Comment by mblackstock** [comment]
Hi Benjamin,
You can send multiple points to a single measurement, but not to multiple measurements in one go yet.  I'm thinking of adding that to a future version.
I'd like to see if I can reproduce it.  Do you have a flow that demonstrates the problem handy?  How many points are you sending?

**Comment by bnjroos** [comment]
I've multiple sensors and I'd like to get their value at a sampling rate of 1s for example. Actually in my real flow I query them on after another so it is working a bit better. However here is an example that reproduces my issue, even with 4 measurements at the same time I get a timeout error:
![chrome_2017-03-07_12-55-50](https://cloud.githubusercontent.com/assets/12064956/23643643/90556cd2-0335-11e7-98df-d1877bcf72b8.png)

Here is my flow:
`[{"id":"9726a7ec.2bc6c8","type":"function","z":"ee432465.bc1328","name":"input2mqtt_influxdb","func":"var valueName = \"Temp_7\";\nvar info = msg.payload;\nvar msg_array = [];\nvar temp_msg = {};\ntemp_msg.payload = valueName+\":\"+info;\nmsg_array.push(temp_msg);\nvar temp_msg = {};\ntemp_msg.measurement = valueName;\ntemp_msg.payload = {\n\tnumValue: info\n}\nmsg_array.push(temp_msg);\nreturn msg_array;","outputs":"2","noerr":0,"x":292.20001220703125,"y":418,"wires":[[],[]]},{"id":"25c56352.7ebd5c","type":"function","z":"ee432465.bc1328","name":"input2mqtt_influxdb","func":"var valueName = \"Temp_6\";\nvar info = msg.payload;\nvar msg_array = [];\nvar temp_msg = {};\ntemp_msg.payload = valueName+\":\"+info;\nmsg_array.push(temp_msg);\nvar temp_msg = {};\ntemp_msg.measurement = valueName;\ntemp_msg.payload = {\n\tnumValue: info\n}\nmsg_array.push(temp_msg);\nreturn msg_array;","outputs":"2","noerr":0,"x":292.20001220703125,"y":358,"wires":[[],[]]},{"id":"27438150.519c9e","type":"function","z":"ee432465.bc1328","name":"input2mqtt_influxdb","func":"var valueName = \"Temp_5\";\nvar info = msg.payload;\nvar msg_array = [];\nvar temp_msg = {};\ntemp_msg.payload = valueName+\":\"+info;\nmsg_array.push(temp_msg);\nvar temp_msg = {};\ntemp_msg.measurement = valueName;\ntemp_msg.payload = {\n\tnumValue: info\n}\nmsg_array.push(temp_msg);\nreturn msg_array;","outputs":"2","noerr":0,"x":292.20001220703125,"y":298,"wires":[[],["13982159.032daf"]]},{"id":"b461029b.24d38","type":"function","z":"ee432465.bc1328","name":"input2mqtt_influxdb","func":"var valueName = \"Temp_4\";\nvar info = msg.payload;\nvar msg_array = [];\nvar temp_msg = {};\ntemp_msg.payload = valueName+\":\"+info;\nmsg_array.push(temp_msg);\nvar temp_msg = {};\ntemp_msg.measurement = valueName;\ntemp_msg.payload = {\n\tnumValue: info\n}\nmsg_array.push(temp_msg);\nreturn msg_array;","outputs":"2","noerr":0,"x":292.20001220703125,"y":238,"wires":[[],["13982159.032daf"]]},{"id":"b970bfce.3be9c","type":"function","z":"ee432465.bc1328","name":"input2mqtt_influxdb","func":"var valueName = \"Temp_3\";\nvar info = msg.payload;\nvar msg_array = [];\nvar temp_msg = {};\ntemp_msg.payload = valueName+\":\"+info;\nmsg_array.push(temp_msg);\nvar temp_msg = {};\ntemp_msg.measurement = valueName;\ntemp_msg.payload = {\n\tnumValue: info\n}\nmsg_array.push(temp_msg);\nreturn msg_array;","outputs":"2","noerr":0,"x":292.20001220703125,"y":178,"wires":[[],["13982159.032daf"]]},{"id":"e0c0953f.1c0bb8","type":"function","z":"ee432465.bc1328","name":"input2mqtt_influxdb","func":"var valueName = \"Temp_2\";\nvar info = msg.payload;\nvar msg_array = [];\nvar temp_msg = {};\ntemp_msg.payload = valueName+\":\"+info;\nmsg_array.push(temp_msg);\nvar temp_msg = {};\ntemp_msg.measurement = valueName;\ntemp_msg.payload = {\n\tnumValue: info\n}\ntemp_msg.measurement = valueName;\nmsg_array.push(temp_msg);\nreturn msg_array;","outputs":"2","noerr":0,"x":292.20001220703125,"y":118,"wires":[[],["13982159.032daf"]]},{"id":"5ce7aa91.3a4f04","type":"function","z":"ee432465.bc1328","name":"input2mqtt_influxdb","func":"var valueName = 'Temp_1';\nvar info = msg.payload;\nvar msg_array = [];\nvar temp_msg = {};\ntemp_msg.payload = valueName+\":\"+info;\nmsg_array.push(temp_msg);\nvar temp_msg = {};\ntemp_msg.measurement = valueName;\ntemp_msg.payload = {\n\tnumValue: info\n}\nmsg_array.push(temp_msg);\nreturn msg_array;","outputs":"2","noerr":0,"x":292.20001220703125,"y":58,"wires":[[],["716119cd.aee9d8","13982159.032daf"]]},{"id":"13982159.032daf","type":"influxdb out","z":"ee432465.bc1328","influxdb":"66c43061.3480d","name":"benji-db","measurement":"","x":554.2000274658203,"y":57.19999694824219,"wires":[]},{"id":"a5a954bb.ad59e8","type":"inject","z":"ee432465.bc1328","name":"","topic":"","payload":"30","payloadType":"num","repeat":"1","crontab":"","once":false,"x":108.5,"y":55.79999542236328,"wires":[["5ce7aa91.3a4f04","e0c0953f.1c0bb8","b970bfce.3be9c","b461029b.24d38","27438150.519c9e","25c56352.7ebd5c","9726a7ec.2bc6c8","f2bf8353.ff2c"]]},{"id":"716119cd.aee9d8","type":"debug","z":"ee432465.bc1328","name":"","active":true,"console":"false","complete":"false","x":588.4999847412109,"y":136.8000030517578,"wires":[]},{"id":"f2bf8353.ff2c","type":"function","z":"ee432465.bc1328","name":"input2mqtt_influxdb","func":"var valueName = \"Temp_8\";\nvar info = msg.payload;\nvar msg_array = [];\nvar temp_msg = {};\ntemp_msg.payload = valueName+\":\"+info;\nmsg_array.push(temp_msg);\nvar temp_msg = {};\ntemp_msg.measurement = valueName;\ntemp_msg.payload = {\n\tnumValue: info\n}\nmsg_array.push(temp_msg);\nreturn msg_array;","outputs":"2","noerr":0,"x":290.20001220703125,"y":474.20001220703125,"wires":[[],[]]},{"id":"66c43061.3480d","type":"influxdb","z":"","hostname":"benji-db","port":"8086","protocol":"http","database":"iotdb","name":"Sensa-db"}]`

I'm thinking of saving the points with their time and send the different measurements not at once but in sequence. Too bad for realtime monitoring, it will be near real time.
Thnak you for your help.

**Comment by mblackstock** [comment]
Thanks I will have a look as soon as I can

**Comment by mblackstock** [comment]
Just tried your flow against a test server and it seems to work OK at my end.  It's an amazon t2.micro instance running influxdb 1.1, so pretty small, but the flow was the only traffic.  Perhaps something to do with your server or network?

**Comment by bnjroos** [comment]
I'm using a docker container on a Rpi3, maybe that is the issue. The node-red is on another container. Thank you, I will do some more tests.

**Comment by mblackstock** [comment]
That's probably it.  Cheers!

**Comment by mblackstock** [comment]
I just published a new version of the node (0.1.0).  You can now insert points to multiple measurements in one go using an 'influx batch' node.  Hopefully this simplifies things for you

**Comment by bnjroos** [comment]
Thank you very much, it is working perfectly now ! Keep the good work !
