### ISSUE TITLE
Enable time to be specified (incl future time)

### ISSUE THREAD

**Issue by svwhisper** [mblackstock/node-red-contrib-influxdb#61]
There doesn't seem to be a way to specify a time for the data.  I would like to specify a future time for the data to enable me to graph forecast solar power with actual.  I currently insert actual energy and battery state of charge and I would like to also insert forecast state of charge 12 hours ahead.  Influxdb appears to support this but the node doesn't seem to allow me to specify the time.

Am I mistaken?  If not, please consider adding this.

**Comment by mblackstock** [comment]
Please have a look at the README for examples on how the timestamp is set using the output or batch node.
