### ISSUE TITLE
Query returns 'null' even data is available

### ISSUE THREAD

**Issue by box99h** [mblackstock/node-red-contrib-influxdb#64]
Hi,

I'm trying to query the max value of my measurements grouped by 7 days. 
To achieve this im using this code:
`SELECT MAX("value") FROM anydata GROUP BY time(7d) `

The code seems to work partially OK but from one point (in this case after 2020-06-18) onwards all values are returned as null. 
This is how it looks like
<img width="277" alt="Bildschirmfoto 2020-07-21 um 12 03 43" src="https://user-images.githubusercontent.com/45336212/88041147-4393ce80-cb4a-11ea-95b1-fcf4066da7af.png">

Same query executed as a table in Grafana returns this:
<img width="737" alt="Bildschirmfoto 2020-07-21 um 12 06 04" src="https://user-images.githubusercontent.com/45336212/88041378-95d4ef80-cb4a-11ea-978b-e8d7ef6bb08a.png">

Data is available but somehow not queried using the node-red module.
Any ideas about that? 
Thank you

**Comment by mblackstock** [comment]
It's not clear this is the same query.  The values returned in the grafana table don't correspond to those in the node-red debug output - they are integers, not float values, and different numbers altogether.  Are you sure there is no difference in the query?
