### ISSUE TITLE
Add support for Complete node (successful transfer)

### ISSUE THREAD

**Issue by DandyDiamond** [mblackstock/node-red-contrib-influxdb#65]
Hi,

I was trying to queue data for InfluxDB and using Catch/Complete nodes to monitor if the data had successfully reached the database or not.

It would be great for future users if the Complete Node could be supported.

Thank you,
Colin

**Comment by JsBergbau** [comment]
I've just found my way here, because I need the same feature. Please add support for complete node, when data was successfully written without any errors. Otherwise throw an error which can be catched by cache node, but that is already implemented. 

You finde the documentation and how to implement it here https://nodered.org/blog/2019/09/20/node-done

Looking forward to have it implemented soon.

**Comment by colinl** [comment]
I was just coming to add a feature request for this only to find it has already been implemented.  Great.
A question, does it call `done()` and `error()` in the case of an error or just  `error()`?
Also is there a timescale for release please?

**Comment by mblackstock** [comment]
It calls `done(err)` as described in [the blog](https://nodered.org/blog/2019/09/20/node-done). 
 Testing would be appreciated, just install it from the develop branch.  Given all the possible configs,  testing takes time.  To install try:

    npm install git://github.com/mblackstock/node-red-contrib-influxdb.git#develop

I am hoping to also improve the query editor text field #84  before publishing the next rev.  Hopefully this week, but might be next week.

**Comment by colinl** [comment]
Excellent, it all seems to be working as I would expect (though only able to test with influx 1.8).  I have checked all three nodes with a number of failure modes, though no doubt there are others I have not thought of.
It would be useful to mention in the docs that the node will only trigger Complete or Catch but never both as knowing that can simplify flows.

**Comment by mblackstock** [comment]
Cool. Thanks for testing!  I will do that.
