### ISSUE TITLE
Unable to write null values to db

### ISSUE THREAD

**Issue by colinl** [mblackstock/node-red-contrib-influxdb#7]
I find I am unable to push null values to the db. Sending a message {topic: some_topic, payload: null} results in the error 
`Error: {"error":"unable to parse 'tydwr value=null': invalid number"}`
Here is a sample flow:
[
    {
        "id": "d1592df1.f9427",
        "type": "inject",
        "z": "e122f88c.3fc3c8",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 189.5,
        "y": 1141,
        "wires": [
            [
                "8d921e96.1de868"
            ]
        ]
    },
    {
        "id": "8d921e96.1de868",
        "type": "function",
        "z": "e122f88c.3fc3c8",
        "name": "Null payload",
        "func": "msg = {topic: \"bedroom/radtemp\", payload: null}\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 377.5,
        "y": 1140,
        "wires": [
            [
                "e18ce4c0.21f96",
                "eeb056ca.f8c358"
            ]
        ]
    },
    {
        "id": "eeb056ca.f8c358",
        "type": "debug",
        "z": "e122f88c.3fc3c8",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "true",
        "x": 722.5,
        "y": 957,
        "wires": []
    },
    {
        "id": "e18ce4c0.21f96",
        "type": "influxdb out",
        "z": "e122f88c.3fc3c8",
        "influxdb": "55ac6d48.e3ffbc",
        "name": "",
        "measurement": "tydwr",
        "x": 994,
        "y": 469,
        "wires": []
    },
    {
        "id": "55ac6d48.e3ffbc",
        "type": "influxdb",
        "z": "",
        "hostname": "127.0.0.1",
        "port": "8086",
        "protocol": "http",
        "database": "tydwr",
        "name": "localhost_tydwr"
    }
]

**Comment by mblackstock** [comment]
Thanks for the report.  I've reproduced the issue.  Unfortunately, as I understand it, influxdb 1.0 and later does not support sending a point with null values.  If you want to indicate that a value is missing, one suggested technique is that you use another field to indicate missing data.

https://docs.influxdata.com/influxdb/v1.0/introduction/getting_started/ "...with InfluxDB, you can have millions of measurements, you don’t have to define schemas up-front, and null values aren’t stored."

see these links for more information.
http://glasnt.com/blog/2015/05/08/influxdb-and-nulls.html
https://github.com/influxdata/influxdb/pull/2429
https://github.com/influxdata/docs.influxdata.com/issues/717
https://github.com/influxdata/influxdb/issues/454

This one discusses techniques for indicating missing data: https://groups.google.com/forum/#!topic/influxdb/L2_JkanwwOY

Sorry!

**Comment by colinl** [comment]
How very odd that they should have removed this capability.  Sorry for wasting your time.
Thanks for a very useful node by the way.

**Comment by mblackstock** [comment]
No problem at all!  Yes, it is odd...  let me know if you see any other issues or enhancement requests.
