### ISSUE TITLE
Influxdb V2 Datatype 

### ISSUE THREAD

**Issue by msommerx** [mblackstock/node-red-contrib-influxdb#71]
Don't know if this is a nodered problem or Influxdb V2 problem.
Adding temperature values to a V2 bucket is a problem, if the first value was integer and another value is float. 

I wasn't facing this problem before V2.

`"Error: 500 Internal Server Error : {"code":"internal error","message":"unexpected error writing points to database: partial write: field type conflict: input field \"ITE05_P\" on measurement \"ITE05\" is type float, already exists as type integer dropped=1"}"`

Any advise?

**Comment by Marooned-MB** [comment]
When storing data in 1.8-flux it's exactly the same problem. I'm storing temperature and if the first value is nice and round like 20, Influx will set field type as integer, so when next values with decimal (eg. 20.1) comes in, we get an error as above.
I could not find a way to force field to be float as JavaScript does not differ integers from float - it's just Number. Passing `val.toFixed(2)` changes it to string.

**Comment by mblackstock** [comment]
I can see the issue.  The code uses Number.isInteger() which returns true if the value can be stored in an integer, so we then attempt to write an integer.

One fix may be to always write float values if we have a number.  To write integers, perhaps we can use a string with an 'i' suffix.  e.g. '12345i' would be an integer, whereas 12345 would always be a float.
