### ISSUE TITLE
node red: deploy failure no response from server

### ISSUE THREAD

**Issue by branteforest** [mblackstock/node-red-contrib-influxdb#76]
Hi There.

When I install node-red-contrib-influxdb I pick up a problem with deploy button. I get an error "node red: deploy failure no response from server"
I then have to switch between Full Deploy or Modified Deploy in order to get the nodes deployed. 

When I remove node-red-contrib-influxdb, the problem goes away. I tried on two node-red installs, one on RPI and other on a vm.

Versions:
node-red-contrib-influxdb - 0.5.1
Node version - v12.19.1
Npm Version - 6.14.8
Ubuntu version - 20.04.1 LTS
Node-Red version - 1.2.3

**Comment by mblackstock** [comment]
I tried installing the node on a ubuntu 20.10 fresh node-red install 1.2.5 same node versions and a flow deployed OK.  Perhaps something has been fixed in the later version of Node-RED but I doubt that's the issue.  Is there a specific flow that this happens with?  Is there any information on the console that is displayed when it happened?

**Comment by branteforest** [comment]
I upgraded my node-red to 1.2.5 with same issue. nothing in console. I dont even add any node-red-contrib-influxdb nodes. When I install with this command, then this happens. "npm install node-red-contrib-influxdb"

<img width="1080" alt="Screenshot 2020-11-21 at 20 34 06" src="https://user-images.githubusercontent.com/49812146/99884707-f9764300-2c38-11eb-9fbc-788956f1a8b3.png">
<img width="1080" alt="Screenshot 2020-11-21 at 20 34 12" src="https://user-images.githubusercontent.com/49812146/99884712-0004ba80-2c39-11eb-8bcd-ae3b7b0c0c97.png">

**Comment by mblackstock** [comment]
odd. Did you install it with the palette manager user interface or using the 'npm install' command you mentioned?
This looks like a fairly complex flow.  Are you only using the nodes you show here, or have you installed any other nodes?  I'll try to do more testing this weekend to see if I can reproduce it.

**Comment by branteforest** [comment]
Thank you.

I did a clean install from scratch and it seems to be working now. Thank you for the support
