### ISSUE TITLE
Is there a way to specify the organization and bucket when using the 2.0 version?

### ISSUE THREAD

**Issue by Frogmore42** [mblackstock/node-red-contrib-influxdb#77]
I was getting this error:
```
ERROR: Write to InfluxDB failed. { Error: 404 Not Found : {"code":"not found","message":"organization name \"organisation\" not found"}
    at IncomingMessage.o.on (/root/.node-red/node_modules/@influxdata/influxdb-client/dist/index.js:16:9212)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  statusCode: 404,
  statusMessage: 'Not Found',
  body:
   '{"code":"not found","message":"organization name \\"organisation\\" not found"}',
  message:
   '404 Not Found : {"code":"not found","message":"organization name \\"organisation\\" not found"}',
  _retryAfter: 0 }
```
So I created the organization of "organisation" (sic) which then got me to:
```
ERROR: Write to InfluxDB failed. { Error: 404 Not Found : {"code":"not found","message":"bucket \"bucket\" not found"}
    at IncomingMessage.o.on (/root/.node-red/node_modules/@influxdata/influxdb-client/dist/index.js:16:9212)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  statusCode: 404,
  statusMessage: 'Not Found',
  body:
   '{"code":"not found","message":"bucket \\"bucket\\" not found"}',
  message:
   '404 Not Found : {"code":"not found","message":"bucket \\"bucket\\" not found"}',
  _retryAfter: 0 }
```
Looking here: https://github.com/mblackstock/node-red-contrib-influxdb/blob/master/influxdb.html
at line 288, I see:
```
            org: {value: "organisation",
                validate:function(org) {
                    if (selectedVersion() === 'v2.0') {
                        return org.length > 0;
                    }
                    return true;
                }
            },
            bucket: {value: "bucket",
                validate:function(bucket) {
                    let version = selectedVersion()
                    if (version === 'v2.0') {
                        return bucket.length > 0;
                    }
                    return true;
                }
            }
```
I am assuming that there is supposed to be some UI for setting this.  I would expect it to be in the config node.  I do finally see the Version combobox (had to uninstall and install a couple of times to get it to show up).  There is also a field for Token and Name.  I suppose I could also create a bucket bucket and get my data that way.

**Comment by Frogmore42** [comment]
It is also possible that I am "not holding it right".  If so please let me know how to hold it.  I looked at all the documentation that I could find, but was not able to figure it out yet.

**Comment by Frogmore42** [comment]
When I added the "bucket" bucket, I started getting "insufficient permissions".  I created a new token and put that in the config node and now I have data in influxdb v2.0.2.

So that is great.  I still think some people might want to set the organization and bucket to something other than "organisation" and "bucket".  But, this does work for now.

**Comment by mblackstock** [comment]
I fixed a bug related to the UI not working correctly when the config node was renamed.  If you install it manually you can try it out.  `npm install mblackstock/node-red-contrib-influxdb`.  Will do another release soon.  To work around it, you can remove the name of the config node as well.  Sorry for the trouble, and let me know if that works for you.

**Comment by Frogmore42** [comment]
Thanks for the tip.  I see the UI now when I remove the Name in the config node, did not notice that before.  Thanks for fixing it too.
