### ISSUE TITLE
Original msg object is not thrown on error, violating Node-RED API specification.

### ISSUE THREAD

**Issue by JsBergbau** [mblackstock/node-red-contrib-influxdb#78]
Take this example node. Use a influx config that doesn't work to trigger the catch node
![grafik](https://user-images.githubusercontent.com/37013344/101398270-19ab3080-38ce-11eb-8243-a4dfbf355ae5.png)

```javascript
[{"id":"b9c368a.13eff98","type":"influxdb out","z":"370bd9c4.98e0ee","influxdb":"f1b4eaef.a4fb88","name":"","measurement":"","precision":"","retentionPolicy":"","database":"database","precisionV18FluxV20":"ms","retentionPolicyV18Flux":"","org":"organisation","bucket":"bucket","x":910,"y":420,"wires":[]},{"id":"203900a6.895a58","type":"change","z":"370bd9c4.98e0ee","name":"Add timestamp","rules":[{"t":"set","p":"measurement","pt":"msg","to":"tempMeasurement","tot":"str"},{"t":"set","p":"payload","pt":"msg","to":"[\t{\t    \"ppm\" : **.payload,\t    \"time\" : ($floor($millis()/60000))*60+60\t    },\t    \t    {\t        \"Sensor\" : \"livingroom\"\t    }\t    \t]","tot":"jsonata"},{"t":"set","p":"precision","pt":"msg","to":"s","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":460,"y":420,"wires":[["b9c368a.13eff98","12242c10.f15f4c"]]},{"id":"59719ba.b0218e4","type":"inject","z":"370bd9c4.98e0ee","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"600","payloadType":"str","x":210,"y":420,"wires":[["203900a6.895a58"]]},{"id":"99b4438c.da4b58","type":"catch","z":"370bd9c4.98e0ee","name":"","scope":["b9c368a.13eff98"],"uncaught":false,"x":240,"y":520,"wires":[["bfb00c36.75b37"]]},{"id":"b373db0a.6e68a","type":"debug","z":"370bd9c4.98e0ee","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":650,"y":520,"wires":[]},{"id":"bfb00c36.75b37","type":"function","z":"370bd9c4.98e0ee","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":440,"y":520,"wires":[["b373db0a.6e68a"]]},{"id":"12242c10.f15f4c","type":"debug","z":"370bd9c4.98e0ee","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":700,"y":360,"wires":[]},{"id":"f1b4eaef.a4fb88","type":"influxdb","hostname":"192.168.0.5","port":"8086","protocol":"http","database":"my_db","name":"","usetls":false,"tls":"46d32926.4dead8","influxdbVersion":"1.x"},{"id":"46d32926.4dead8","type":"tls-config","name":"","cert":"","key":"","ca":"","certname":"m2mqtt_srv.crt","keyname":"m2mqtt_srv.key","caname":"m2mqtt_ca.crt","verifyservercert":false}]
```
This flow adds a timestamp to every measurement.

Why is this imporant for me? With that catchnode I want to catch write errors when the database is down, e.g. for maintenance. Then catch node catches the message, it is written to a text file and then I can manually import it (or also automate that when it is working correctly). To use this flow correctly it is imporant that original timestamp is preserved, however timestamp is removed, making this flow useless.

Output from first debug node
![grafik](https://user-images.githubusercontent.com/37013344/101398625-ab1aa280-38ce-11eb-9504-00d9a92a1e76.png)

Output from second debug node, notice timestamp is gone/missing

![grafik](https://user-images.githubusercontent.com/37013344/101398675-be2d7280-38ce-11eb-8991-e1884933aac0.png)

This behaviour is also violating Node-RED API, since the original msg object should be thrown, see https://nodered.org/docs/user-guide/writing-functions#handling-errors also see https://github.com/node-red/node-red-nodes/pull/653 Where is again clearly stated that original message has to be passed.

Hope that can be fixed soon, so no measurement will be lost again.

**Comment by mblackstock** [comment]
Thanks for this report.

When the error occurs, we call `node.error(err,msg)` as expected.  The bug is that we're modifying the message to prepare it to send to the InfluxDb API rather than creating new object.  When the error occurs, we return a message that has been modified, e.g. converting strings to integers, and removing the time field.
