### ISSUE TITLE
Dynamic queries

### ISSUE THREAD

**Issue by ederfdias** [mblackstock/node-red-contrib-influxdb#79]
Can I run a dynamic queries with Influxdb in node?
For example: 
Select * from " + msg.payload["measurement_name"] + " where time > now() -1"

Thanks a lot!

**Comment by mblackstock** [comment]
Yes, you can use a function node to assign your dynamic query to the `msg.query` property rather than setting the query in the input node configuration.  There is an example of this in the README.
