### ISSUE TITLE
TypeError on usage readme example

### ISSUE THREAD

**Issue by darwin10** [mblackstock/node-red-contrib-influxdb#81]
using one of the readme examples for writing and influxdb 2, the node returns TypeError: this.writeBuffer.flush(...).finally is not a function"

ver 0.5.3, tried back to 0.5.0 but the error is still present. 

influxdb 2.0.3

**Comment by mblackstock** [comment]
Thanks for the report I will check it out.  Can you tell me the example you were trying, what version of Node you were using?  This might save me a bit of time.

**Comment by mblackstock** [comment]
I can see this error when I run Node-RED with Node.js v 8.17.0, but not when I use 10.23.0 or 14.15.1.  Can you make sure you're using Node 10.x or later?  The Node-RED site recommends using Node 12.x LTS.

**Comment by darwin10** [comment]
Thanks, that appears to be the issue, might I suggest a version check to error the node on less than 10.x. as Node-RED itself can run on earlier versions.

**Comment by mblackstock** [comment]
Yes, I will add that to the package. It looks like Node-RED supports 8.x
but is no longer maintaining it, so probably a good idea to upgrade soon
anyway.

**Comment by mblackstock** [comment]
see #82
