### ISSUE TITLE
node-red-contrib-influxdb:influxdb : Error: No valid exports main found

### ISSUE THREAD

**Issue by mrvic** [mblackstock/node-red-contrib-influxdb#83]
### node-red-contrib-influxdb:influxdb : Error: No valid exports main found

31 Dec 11:02:46 - [info] Installing module: node-red-contrib-influxdb, version: 0.5.3
31 Dec 11:02:51 - [info] Installed module: node-red-contrib-influxdb
31 Dec 11:02:52 - [info] Added node types:
```
31 Dec 11:02:52 - [info]  - node-red-contrib-influxdb:influxdb : Error: No valid exports main found for 'C:\Users\pmrvic\node_modules\@influxdata\influxdb-client' (line:6)
31 Dec 11:02:52 - [info]  - node-red-contrib-influxdb:influxdb out : Error: No valid exports main found for 'C:\Users\pmrvic\node_modules\@influxdata\influxdb-client' (line:6)
31 Dec 11:02:52 - [info]  - node-red-contrib-influxdb:influxdb batch : Error: No valid exports main found for 'C:\Users\pmrvic\node_modules\@influxdata\influxdb-client' (line:6)
31 Dec 11:02:52 - [info]  - node-red-contrib-influxdb:influxdb in : Error: No valid exports main found for 'C:\Users\pmrvic\node_modules\@influxdata\influxdb-client' (line:6)
```

**Comment by mblackstock** [comment]
Thanks for the report.  Can you tell me what version of node you are using?

**Comment by mblackstock** [comment]
I have reproduced this with node version 13.5.0.
I cannot reproduce it with version 10.23.0, or version 14.15.3
Currently this node does not support version 8.x as mentioned in #81 
Based on similar issues on the web, I suggest that upgrading to the latest LTS version of node will fix this issue.  Will close until I hear back otherwise.

**Comment by mrvic** [comment]
Hello, thank you. upgrade to latest node solved issue!
Best regards,
