### ISSUE TITLE
unsupported input type for mean aggregate: string

### ISSUE THREAD

**Issue by kaciker** [mblackstock/node-red-contrib-influxdb#87]
I'm trying to insert string in Influxdb v2 (2.0.3)
When I send a msg, like:

msg.payload = [{
    intValue: '10i',
    numValue: 12,
    randomValue: Math.random()*10,
    strValue: "message2"
},
{
    tag1:"sensor1",
    tag2:"device2"
}];
return msg;

And when I check the "strValue" the result in the CLI InfluxDB is: unsupported input type for mean aggregate: string
![2021-01-25_13h00_06](https://user-images.githubusercontent.com/7668181/105703344-5d550a80-5f0d-11eb-89d5-3fd12a49da48.png)

**Comment by mblackstock** [comment]
I can't see the query in the query in the Data Explorer screenshot you
provided nor a CLI command.  I suspect that in your query you're trying to
get the mean/average of a string value somehow, which will not work of
course.  You can only average numeric values.

I don't think this is an issue with the node.

**Comment by kaciker** [comment]
You're right... only changing to last is workin, I'm sorry

**Comment by mblackstock** [comment]
no worries.  Glad you sorted it
