### ISSUE TITLE
Export influxdb credentials token

### ISSUE THREAD

**Issue by EnricoBeltramo** [mblackstock/node-red-contrib-influxdb#92]
When I export and re-import a flow contains influxdb out look the token to access to db is not saved and I have to reconfigure it again. There is a way to export access credentials too?

**Comment by mblackstock** [comment]
Credentials are not copied when you export a flow so that they are not exposed. Credentials are saved in a separate file by design (Node-RED design, not this node).  See https://discourse.nodered.org/t/how-to-copy-credentials-in-node-red-flow/23315 for a discussion on this.
