### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [mblackstock/node-red-contrib-influxdb#95]
Hello
We are getting this error
```Error: write EPROTO 139671178012544:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:````
we have an influxdb2 server with ssl and a self signed certificate; so we need https but not to verify the certificate.

This is what happens when we try to write to the db with those settings.

Thanks,

**Comment by mblackstock** [comment]
Sorry for the trouble.  Are you able to connect to the server from another HTTP client using SSL (e.g. using curl --insecure)?  Can you ensure "Verify Server Certificate" is not checked in your configuration node?  Thanks

**Comment by mirkocomparetti-synesis** [comment]
No problem.
I am really sorry, but it works like a charm.
I realized just now that I had a typo in the IP of the machine with influxdb2 with ssl and I was pointing to the wrong one (one that is running influxdb1 without ssl).
It's my bad... really really sorry I bothered!
